apiVersion: apps/v1
kind: Deployment
metadata:
  name: hvac-controller
  labels:
    app: hvac
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hvac
  template:
    metadata:
      labels:
        app: hvac
    spec:
      containers:
      - name: hvac-controller
        image: olsenjoseph/oxygencs-app:oxygencs-py
        resources:
          limits:
            cpu: "0.1"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        ports:
        - containerPort: 8080
