name: Oxygencs python CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies and tools
      run: |
        pip install -r requirements.txt
        pip install flake8 black

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install flake8 and black
      run: |
        pip install flake8 black

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --max-complexity=10 --max-line-length=127 --exit-zero

    - name: Format code with Black
      run: black --diff src

  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            olsenjoseph/oxygencs-app:oxygencs-py
            olsenjoseph/oxygencs-app:latest

      - name: Extract image name
        id: extract_image_name
        run: echo "::set-output name=image_name::olsenjoseph/oxygencs-app:oxygencs-py"

      - name: Set up KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          cp kubeconf.yaml $HOME/.kube/config
        shell: bash

      - name: Deploy to Kubernetes
        run: |
          DEPLOYMENT_NAME=hvac-controller
          IMAGE_NAME=${{ steps.extract_image_name.outputs.image_name }}
          NAMESPACE=grp02eq6-namespace

          if kubectl --kubeconfig=$HOME/.kube/config get deployment $DEPLOYMENT_NAME -n $NAMESPACE &>/dev/null; then
            kubectl --kubeconfig=$HOME/.kube/config set image deployment/$DEPLOYMENT_NAME hvac-controller=$IMAGE_NAME -n $NAMESPACE
          else
            kubectl --kubeconfig=$HOME/.kube/config apply -f hvac-controller-deployment.yaml -n $NAMESPACE
          fi

          sleep 30

          kubectl --kubeconfig=$HOME/.kube/config get pods -l app=$DEPLOYMENT_NAME -n $NAMESPACE
